# Generated by Django 5.2.8 on 2025-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenting',
            field=models.CharField(max_length=230),
        ),
    ]
