# Generated by Django 5.2.8 on 2025-11-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_comment_commenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatpost',
            name='Chat',
            field=models.CharField(max_length=500),
        ),
    ]
